base_config:
  - ./svc_base.yaml

audio_sample_rate: 44100
hop_size: 512
sampling_steps: 20
K_step: 400
# max_batch_frames: 每 batch 最大帧数
max_batch_frames: 16000
max_batch_size: 24

binary_data_dir: data/svc_quality/megumin

# noe
binarization_args:
  shuffle: true
  num_workers: 2
pe_ckpt: ckpt/rmvpe/model.pt
vocoder_ckpt: ckpt/vocoder/pc_nsf_hifigan_44.1k_hop512_128bin_2025.02/model.ckpt
contentvec:
  checkpoint_path: ckpt/contentvec/lengyue233_cvec-best.bin

datasets:
  # === 在这里添加你的数据集 ===
  # 每个说话人一个条目，示例：
  - raw_data_dir: data/megumin
    speaker: megumin
    spk_id: 0
    language: jp
    artifact_level: 0  # 0 = 高质量干声, 1 = 有瑕疵/拼接数据
    test_prefixes:
      - '@val_'
num_spk: 1

val_with_vocoder: true
# val_check_interval: 验证间隔（默认 2000 步）
val_check_interval: 10000
num_valid_plots: 10

# max_updates: 总训练步数（默认 160000）
max_updates: 160000
num_ckpt_keep: 3
permanent_ckpt_start: 60000
permanent_ckpt_interval: 10000
pl_trainer_devices: auto
# pl_trainer_precision: 训练精度（默认 16-mixed）
pl_trainer_precision: 16-mixed
